spring.application.name=api-gateway
server.port=4004

# Auth Service Configuration
auth.service.url=http://auth-svc:8084

# -----------------------------
# Patient Service Route
# -----------------------------
spring.cloud.gateway.routes[0].id=patient-service-route
spring.cloud.gateway.routes[0].uri=http://patient-svc:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=JwtValidation

# -----------------------------
# Auth Service Route
# -----------------------------
spring.cloud.gateway.routes[1].id=auth-service-route
spring.cloud.gateway.routes[1].uri=http://auth-svc:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# -----------------------------
# Patient Swagger Docs
# -----------------------------
spring.cloud.gateway.routes[2].id=patient-api-docs
spring.cloud.gateway.routes[2].uri=http://patient-svc:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api-docs/patients
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api-docs/patients,/v3/api-docs